/**
 * Receipt helpers. The receipt code is an 8-char uppercase alphanumeric
 * slug generated by Postgres on the first paid transition of an order.
 * The public URL is /r/{code} and is accessible without authentication.
 */

export function buildReceiptPath(code: string): string {
  return "/r/" + code;
}

export function buildReceiptUrl(origin: string, code: string): string {
  return origin + buildReceiptPath(code);
}

/**
 * Build the WhatsApp deep-link a vendor taps to send a receipt to a customer.
 * Prefilled with the customer name and the receipt URL.
 */
export function buildReceiptWhatsAppMessage(args: {
  businessName: string;
  customerName: string;
  receiptUrl: string;
}): string {
  return (
    "Hi " + args.customerName + ", here is your receipt from " +
    args.businessName + ": " + args.receiptUrl
  );
}
